# Generated by Django 4.0.5 on 2022-08-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('mensaje', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
