# Generated by Django 4.0.5 on 2022-08-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='mensaje',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
